baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "MAT 219 Data Science"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Grant Innerst"
  bio = ""
  job = "Assistant Professor of Mathematics"
  location = "Shippensburg University"
  gravatarEmail = "glinnerst@ship.edu"
  # Your profile picture
#  picture = ""
  twitter = "GrantInnerst"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "syllabus"
  name = "Daily Schedule"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 3
  identifier = "rstudio"
  name = "RStudio"
  pre = "<i class=\"material-icons\">cloud_queue</i>"
  url = "https://rstudio.cloud"
[[menu.footer]]
  weight = 2
  name = "RStudio"
  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
  url = "https://rstudio.cloud/"


[params]
  dateFormat = "January 2, 2006"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
