---
title: "Midterm - Open Case Studies Exploration"
format: html
---

## Open Case Studies

The Open Case Studies (OCS) project is an educational resource of experiential guides that demonstrate how to effectively derive knowledge from data in real-world challenges. This project is the result of work of a team of researchers from Johns Hopkins University and it's Principal Investigator Dr. Stephanie Hicks. The project contains 12 different case studies. You can check out the projects and case studies here: https://www.opencasestudies.org/. 


## Midterm Tasks 

For the midterm, you are going to you are going to choose a case study that you want to work with (from the approved list that is listed) below and complete a number of tasks. Specifically, 


1. You need to choose a case study to work with. Here are the list of approved case studies:

- School Shootings in the United States
- Opioids in United States
- Mental Health of American Youth
- Exploring CO2 emissions across time
- Exploring global patterns of dietary behaviors associated with health risk

2. Complete the case study. The studies are really well documented and includes all of the requisite code you will need. You will already know some of the skills from class, but each study contains some new skills. Write down your work in a Quarto document. Make sure to answer all of the questions they ask throughout. The answers are included, but try to answer the questions before you look at the key. 

3. Answer the suggested homework question(s) in the same Quarto document you did #2 in. 

4. Come up with your own question and answer it. Your question should be a "big picture" question, not one that can be answered with a single plot or summary table. 